services:
  app:
    build: .
    container_name: simple-python-server
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:/app
  database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=projects
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - .db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
